### ISSUE TITLE
Desktop replicants are not always detected

### ISSUE THREAD

**Issue by ocerman** [HaikuArchives/Repliman#3]
The problem seems to be in https://github.com/HaikuArchives/Repliman/blob/master/replimanWindow.cpp#L475 , where Tracker's desktop window is being targeted by its title. The problem is when Tracker option "ShowFullPathInTitle" is not selected - because then the window title is different (then it depends also on OS Language).

Does anyone know whether Tracker's desktop window can be targeted in another way?

**Comment by humdingerb** [comment]
One option - though it appears a bit fragile to me - is to use
`
request.AddSpecifier("Window", int32(0));
`
instead, as the Desktop is always Window 0 of Tracker. That'll break tough if Haiku ever changes that. However, it's been a constant since BeOS days, i.e. over 2 decades... :)

**Comment by pulkomandy** [comment]
If Tracker doesn't allow getting a window by filesystem path already, we should add that there.
