### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Repliman#5]
I notice that there isn't license and copyright information in the headers or anywhere.
The code is also hosted by its author at https://github.com/kumo.

@kumo, hope you see this.
Are you OK with HaikuArchives hosting the code?
And would you agree to releasing the code under the MIT license?

**Comment by kumo** [comment]
Hello @humdingerb yes I am fine with HaikuArchives hosting the code, and also for the MIT license

**Comment by humdingerb** [comment]
Thanks very much, @kumo!
